export const services = [
  { slug: 'recurring-cleanup', tag: 'Keep it clean', title: 'Routine yard cleanup', short: 'Recurring cleanup', summary: 'A regular reset for your yard, with weekly, every-other-week, and monthly options.', headline: 'The best backyard chore is the one you don’t have to do.', intro: 'Keep the waste from piling up with a cleanup schedule built around your household. We take care of the regular pickup, and you get a yard that’s easier to enjoy.', image: '/images/yard-dog.jpg', alt: 'Golden retriever standing in a backyard', details: ['Scheduled dog waste pickup in the agreed service area', 'Waste collected and double-bagged with care', 'Equipment cleaned between stops', 'Flexible scheduling without a long-term contract'], fit: 'Dog owners who want ongoing help, busy households, and anyone ready to take scooping off the weekly list.', sections: [['Weekly', 'A consistent weekly visit keeps regular pickup on the calendar. A good place to start when your yard gets daily use.'], ['Every other week', 'A less frequent visit for households that prefer a little space between cleanups. Tell us about your dogs and yard so we can help you compare.'], ['Monthly', 'Occasional scheduled help for lighter-use spaces. We’ll discuss whether the longer interval is a practical fit for your property.']], note: 'Has it been a while since the last cleanup? Let us know. Your first visit may need a different scope than ongoing maintenance.' },
  { slug: 'one-time-cleanup', tag: 'Start fresh', title: 'One-time & spring cleanup', short: 'One-time cleanup', summary: 'A fresh start after winter, before company comes over, or whenever the yard needs extra attention.', headline: 'A fresh start for your favorite outdoor space.', intro: 'When the snow melts or life gets busy, the backyard can need more than a quick scoop. Our one-time service helps you get caught up without signing up for an ongoing schedule.', image: '/images/puppy-grass.jpg', alt: 'A golden retriever puppy exploring the grass', details: ['A cleanup scoped to your yard and its current condition', 'Careful dog waste collection and double-bagging', 'No recurring service required', 'The option to discuss ongoing visits afterward'], fit: 'Spring thaw, preparing for guests, moving into a home with a dog-used yard, or catching up after a busy season.', sections: [['After the thaw', 'Tell us what’s been accumulating over winter and how much of the ground is accessible. We’ll discuss timing and the extent of the cleanup.'], ['Before a gathering', 'Planning to use the yard for company? Share your preferred date early so we can confirm availability.'], ['Whenever you need a hand', 'You don’t need a special occasion to ask for help. A one-time cleanup can simply take an overdue job off your list.']], note: 'Snow cover, tall grass, leaves, and access can affect what we can reach. Share the condition of your yard when requesting your quote.' },
  { slug: 'commercial', tag: 'Shared spaces', title: 'Commercial pet waste care', short: 'Commercial care', summary: 'Thoughtful cleanup for apartment communities, HOAs, rental properties, and shared dog-friendly spaces.', headline: 'Dog-friendly spaces. A better experience for everyone.', intro: 'Shared lawns and pet areas need a consistent plan. We work with property managers and community teams to discuss the spaces, schedule, and cleanup needs that matter to their residents.', image: '/images/dog-walk.jpg', alt: 'A person walking a dog through an outdoor green space', details: ['Cleanup planning for agreed common areas', 'Service frequency discussed around property use', 'Careful collection and double-bagging of pet waste', 'Direct communication with a local service team'], fit: 'Apartment communities, homeowners associations, rental properties, dog parks, and other shared outdoor spaces.', sections: [['Walk the scope', 'Tell us which lawns, pet areas, or common spaces need attention. Acreage, layout, and access help us understand the work.'], ['Choose a cadence', 'High-traffic areas and quieter properties have different needs. We’ll discuss an appropriate visit schedule and quote.'], ['Keep communication simple', 'Share a property contact and any access instructions so the crew and your team have a clear starting point.']], note: 'Commercial pricing is property-specific. Include your property name, approximate size, and preferred frequency in your request.' },
] as const;

export const faqs = [
  { group: 'Getting started', q: 'How much does cleanup cost?', a: 'We provide a free quote based on your property, number of dogs, service frequency, and the amount of cleanup needed. Send your yard details or give us a call. We’ll talk through the scope and price before you start.' },
  { group: 'Getting started', q: 'Do I have to sign a long-term contract?', a: 'No. K9 Kleanup offers service without long-term contracts. If you need to change, pause, or cancel your schedule, contact the team to coordinate the change.' },
  { group: 'Getting started', q: 'What areas do you serve?', a: 'We serve St. Cloud, Sartell, Sauk Rapids, St. Joseph, and surrounding Central Minnesota communities. Coverage depends on your address and the service you need, so send your ZIP code and we’ll confirm.' },
  { group: 'Getting started', q: 'Can I book just one cleanup?', a: 'Yes. One-time cleanups are available for spring catch-up, getting ready for company, moving, or whenever you need help. You don’t have to enroll in a recurring plan.' },
  { group: 'Your service', q: 'How often can you come?', a: 'Weekly, every-other-week, monthly, and one-time options are available. We’ll help you compare the options based on your dogs, yard, and how you use the space.' },
  { group: 'Your service', q: 'Do I need to be home?', a: 'Tell us about your gates, locks, and yard access when you request a quote. We’ll agree on access arrangements before the first visit and let you know whether anything requires you to be there.' },
  { group: 'Your service', q: 'Can my dog stay in the yard during service?', a: 'Please discuss your dogs and their behavior with us before service. We’ll confirm a safe arrangement for your pets and our crew, including whether dogs need to stay inside during the visit.' },
  { group: 'Your service', q: 'How should I prepare my yard?', a: 'Make the agreed cleanup areas accessible and let us know about locked gates or other access issues. Tall grass, heavy leaf cover, and snow can hide waste, so please mention those conditions in advance.' },
  { group: 'Your service', q: 'What happens during snow or severe weather?', a: 'Minnesota weather can affect visibility and safe access to a property. Contact us about current conditions and scheduling. If your yard has winter buildup, ask about a one-time spring cleanup.' },
  { group: 'Care & details', q: 'How do you keep equipment clean?', a: 'We clean our equipment between stops and double-bag collected waste. Our process is built around careful handling and respect for each property.' },
  { group: 'Care & details', q: 'Do you offer deodorizing or sanitation treatments?', a: 'Yes, ask us about available sanitation and deodorizing treatments. We’ll discuss the surface, product, and any application or re-entry instructions before adding a treatment to your service.' },
  { group: 'Care & details', q: 'What if something was missed?', a: 'K9 Kleanup stands behind its work with a satisfaction guarantee. If you have a concern after a visit, contact us with the details so we can discuss making it right.' },
  { group: 'Care & details', q: 'Do you work with property managers?', a: 'Yes. We provide pet waste cleanup for commercial and shared spaces, including apartments, HOAs, rental properties, and dog parks. Tell us about the property and the areas that need attention for a tailored quote.' },
];
