import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { services } from '@/lib/site-content';
import { ClosingCTA, CheckList, QuoteLink } from '@/components/site-sections';
type Props = { params: Promise<{ slug: string }> };
export async function generateMetadata({params}:Props):Promise<Metadata> { const {slug}=await params; const s=services.find(s=>s.slug===slug); return {title:s?.title ?? 'Service not found',description:s?.summary}; }
export default async function Service({params}:Props) {
  const {slug}=await params; const s=services.find(s=>s.slug===slug); if(!s) notFound();
  return <><section className="site-container pt-12 pb-20"><Link href="/services" className="text-sm underline underline-offset-4">← All services</Link><div className="content-grid mt-10 items-center"><div><p className="eyebrow">{s.title}</p><h1 className="section-title">{s.headline}</h1><p className="body-copy mt-7">{s.intro}</p><div className="mt-8"><QuoteLink/></div></div><div className="relative aspect-[4/5] max-h-[600px] overflow-hidden rounded-t-[9rem]"><Image src={s.image} alt={s.alt} fill priority sizes="(max-width: 1024px) 100vw, 50vw" className="photo"/></div></div></section><section className="bg-white section-space"><div className="site-container content-grid"><div><p className="eyebrow">What to expect</p><h2 className="section-title">Thoughtful service.<br/>Clear expectations.</h2><p className="body-copy mt-6">{s.fit}</p></div><CheckList items={[...s.details]}/></div></section><section className="site-container section-space"><p className="eyebrow">Let’s find the right fit</p><div className="grid gap-10 md:grid-cols-3">{s.sections.map(([title,body],i)=><div key={title} className="border-t pt-6"><span className="font-heading text-2xl text-muted-foreground">0{i+1}</span><h2 className="mt-5 font-heading text-3xl">{title}</h2><p className="mt-4 leading-relaxed text-muted-foreground">{body}</p></div>)}</div><aside className="mt-12 border-l-4 border-[#c7a246] bg-[#ecefdf] p-6 leading-relaxed"><strong>Good to know:</strong> {s.note}</aside><div className="mt-14 flex flex-wrap items-center gap-8"><Link href="/faq" className="text-link">More questions? Read our FAQs ↗</Link><Link href="/service-areas" className="text-link">Check our service area ↗</Link></div></section><ClosingCTA/></>;
}
