"use client";
import { useCallback, useEffect, useState, type ReactNode } from "react";
import { adminApiUrl } from "@/lib/admin-api-client";
import type { ReviewSliderSettings, ReviewWidgetType } from "@/lib/google-review-types";
import { GoogleReviewWidget, type ReviewSliderPayload } from "./GoogleReviewSlider";
import styles from "./ReviewSliderAdmin.module.css";

type Location = { name: string; title: string; accountName: string; accountTitle: string };
const widgets: Array<{ value: ReviewWidgetType; label: string; detail: string }> = [
  { value: "carousel", label: "Slider", detail: "One rotating review" }, { value: "cards", label: "Card array", detail: "Responsive equal grid" },
  { value: "masonry", label: "Review wall", detail: "Natural card heights" }, { value: "list", label: "Compact list", detail: "Horizontal rows" },
  { value: "table", label: "Review table", detail: "Dense comparison view" }, { value: "single", label: "Single card", detail: "Focused testimonial" },
  { value: "spotlight", label: "Feature section", detail: "Hero plus supporting cards" }, { value: "badge", label: "Rating badge", detail: "Compact trust mark" },
];
const presets: Array<{ label: string; patch: Partial<ReviewSliderSettings> }> = [
  { label: "Clean cards", patch: { widgetType: "cards", theme: "light", columns: 3, cardRadius: 16, cardGap: 18, cardColor: "#ffffff", textColor: "#173c36" } },
  { label: "Dark spotlight", patch: { widgetType: "spotlight", theme: "dark", cardRadius: 22, cardGap: 14, cardColor: "#183c35", textColor: "#f3fbf8" } },
  { label: "Minimal list", patch: { widgetType: "list", theme: "light", cardRadius: 4, cardGap: 8, showAvatar: false, showGoogleMark: true } },
  { label: "Trust badge", patch: { widgetType: "badge", theme: "light", cardRadius: 40, popupEnabled: true } },
];

export function ReviewSliderAdmin() {
  const [data, setData] = useState<ReviewSliderPayload | null>(null); const [locations, setLocations] = useState<Location[]>([]); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [tab, setTab] = useState<"source" | "layout" | "design" | "popup" | "publish">("source");
  const load = useCallback(async () => { const response = await fetch(adminApiUrl("/api/admin/reviews"), { credentials: "same-origin", cache: "no-store" }); const payload = await response.json() as ReviewSliderPayload & { error?: string }; if (!response.ok) throw new Error(payload.error); setData(payload); }, []);
  useEffect(() => { void load().catch((error) => setMessage(error.message)); }, [load]);
  async function action(actionName: string) { setBusy(true); setMessage(""); try { const response = await fetch(adminApiUrl("/api/admin/reviews"), { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: actionName }) }); const payload = await response.json() as { error?: string; locations?: Location[] }; if (!response.ok) throw new Error(payload.error); if (actionName === "locations") setLocations(payload.locations ?? []); else { await load(); setMessage("Google reviews synchronized."); } } catch (error) { setMessage(error instanceof Error ? error.message : "Request failed."); } finally { setBusy(false); } }
  async function save() { if (!data) return; setBusy(true); try { const selected = locations.find((item) => item.name === data.settings.locationName); const response = await fetch(adminApiUrl("/api/admin/reviews"), { method: "PATCH", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...data.settings, accountName: selected?.accountName }) }); const payload = await response.json() as { error?: string; settings?: ReviewSliderSettings }; if (!response.ok || !payload.settings) throw new Error(payload.error ?? "Review settings response was incomplete."); setData({ ...data, settings: payload.settings }); setMessage("Review widget settings saved."); } catch (error) { setMessage(error instanceof Error ? error.message : "Save failed."); } finally { setBusy(false); } }
  if (!data) return <main className={styles.page}><p>{message || "Loading review widgets…"}</p></main>;
  const settings = data.settings; const update = (patch: Partial<ReviewSliderSettings>) => setData({ ...data, settings: { ...settings, ...patch } });
  return <main className={styles.page}><header><div><p>WEBSITE PROOF</p><h1>Google Review Widgets</h1><span>Build reusable review sections, cards, tables, sliders, badges, and social-proof notifications.</span></div><button className={styles.saveTop} disabled={busy} onClick={() => void save()}>Save changes</button></header>{message ? <div className={styles.notice}>{message}</div> : null}
    <nav className={styles.tabs}>{(["source","layout","design","popup","publish"] as const).map((item) => <button key={item} className={tab === item ? styles.activeTab : ""} onClick={() => setTab(item)}>{item}</button>)}</nav>
    <div className={styles.layout}><aside className={styles.controls}>{tab === "source" ? <SourcePanel data={data} locations={locations} busy={busy} action={action} update={update} /> : null}{tab === "layout" ? <LayoutPanel settings={settings} update={update} /> : null}{tab === "design" ? <DesignPanel settings={settings} update={update} /> : null}{tab === "popup" ? <PopupPanel settings={settings} update={update} /> : null}{tab === "publish" ? <PublishPanel settings={settings} update={update} /> : null}</aside>
      <section className={styles.preview}><div><header><span>LIVE PREVIEW · {widgets.find((item) => item.value === settings.widgetType)?.label}</span><button onClick={() => update({ popupEnabled: !settings.popupEnabled })}>{settings.popupEnabled ? "Popup on" : "Preview popup"}</button></header><GoogleReviewWidget initialData={data} /></div></section></div>
  </main>;
}

function SourcePanel({ data, locations, busy, action, update }: { data: ReviewSliderPayload; locations: Location[]; busy: boolean; action: (name: string) => Promise<void>; update: (patch: Partial<ReviewSliderSettings>) => void }) { const settings = data.settings; return <Panel title="Google review source" description="REGGIE caches approved reviews so public pages never wait for Google.">{data.connected ? <><strong className={styles.connected}>Google Business Profile connected</strong><div className={styles.actions}><button disabled={busy} onClick={() => void action("locations")}>Load locations</button><button disabled={busy || !settings.locationName} onClick={() => void action("sync")}>Sync now</button></div></> : <a className={styles.primary} href={adminApiUrl("/api/admin/google-business/connect")}>Connect Google Business</a>}{locations.length ? <Field label="Business location"><select value={settings.locationName} onChange={(event) => { const item = locations.find((location) => location.name === event.target.value); update({ locationName: item?.name || "", locationTitle: item?.title || "" }); }}><option value="">Choose a location</option>{locations.map((item) => <option key={`${item.accountName}:${item.name}`} value={item.name}>{item.title} · {item.accountTitle}</option>)}</select></Field> : null}<div className={styles.stats}><span><b>{data.reviews.length}</b>displayable</span><span><b>{data.averageRating || "—"}</b>rating</span><span><b>{data.totalReviewCount || "—"}</b>total</span></div><small>{data.syncedAt ? `Last synced ${new Date(data.syncedAt).toLocaleString()}` : "No review sync has completed yet."}</small><div className={styles.two}><Field label="Minimum stars"><select value={settings.minimumRating} onChange={(event) => update({ minimumRating: Number(event.target.value) })}>{[5,4,3,2,1].map((value) => <option key={value}>{value}</option>)}</select></Field><Field label="Review limit"><input type="number" min="1" max="50" value={settings.maximumReviews} onChange={(event) => update({ maximumReviews: Number(event.target.value) })} /></Field></div></Panel>; }

function LayoutPanel({ settings, update }: EditorProps) { return <><Panel title="Widget type" description="One data source powers every placement."><div className={styles.widgetGrid}>{widgets.map((item) => <button key={item.value} className={settings.widgetType === item.value ? styles.selectedWidget : ""} onClick={() => update({ widgetType: item.value })}><b>{item.label}</b><small>{item.detail}</small></button>)}</div></Panel><Panel title="Layout controls"><div className={styles.two}><Field label={`Columns · ${settings.columns}`}><input type="range" min="1" max="4" value={settings.columns} onChange={(event) => update({ columns: Number(event.target.value) })} /></Field><Field label={`Card gap · ${settings.cardGap}px`}><input type="range" min="0" max="48" value={settings.cardGap} onChange={(event) => update({ cardGap: Number(event.target.value) })} /></Field></div><Field label={`Review excerpt · ${settings.excerptLength} characters`}><input type="range" min="80" max="1000" step="20" value={settings.excerptLength} onChange={(event) => update({ excerptLength: Number(event.target.value) })} /></Field></Panel><Panel title="Quick presets"><div className={styles.presetList}>{presets.map((preset) => <button key={preset.label} onClick={() => update(preset.patch)}>{preset.label}</button>)}</div></Panel></>; }

function DesignPanel({ settings, update }: EditorProps) { return <><Panel title="Content"><Field label="Heading"><input value={settings.heading} onChange={(event) => update({ heading: event.target.value })} /></Field><Field label="Subheading"><input value={settings.subheading} onChange={(event) => update({ subheading: event.target.value })} /></Field></Panel><Panel title="Appearance"><div className={styles.two}><Field label="Theme"><select value={settings.theme} onChange={(event) => update({ theme: event.target.value as ReviewSliderSettings["theme"] })}><option value="light">Light</option><option value="dark">Dark</option><option value="brand">Brand</option></select></Field><Field label={`Corners · ${settings.cardRadius}px`}><input type="range" min="0" max="40" value={settings.cardRadius} onChange={(event) => update({ cardRadius: Number(event.target.value) })} /></Field>{(["accentColor","cardColor","textColor"] as const).map((key) => <Field key={key} label={key.replace("Color", " color")}><input type="color" value={settings[key]} onChange={(event) => update({ [key]: event.target.value })} /></Field>)}</div>{(["showAvatar","showDate","showGoogleMark","showRatingSummary"] as const).map((key) => <Check key={key} label={humanize(key)} checked={settings[key]} onChange={(value) => update({ [key]: value })} />)}</Panel><Panel title="Carousel"><Check label="Autoplay slider" checked={settings.autoplay} onChange={(autoplay) => update({ autoplay })} /><Field label={`Advance every ${settings.autoplaySeconds} seconds`}><input type="range" min="3" max="30" value={settings.autoplaySeconds} onChange={(event) => update({ autoplaySeconds: Number(event.target.value) })} /></Field></Panel></>; }

function PopupPanel({ settings, update }: EditorProps) { return <Panel title="Periodic review notification" description="Shows authentic synced reviews with their real date. It never claims an older review happened just now."><Check label="Enable review popup" checked={settings.popupEnabled} onChange={(popupEnabled) => update({ popupEnabled })} /><Check label="Show once per browser session" checked={settings.popupOncePerSession} onChange={(popupOncePerSession) => update({ popupOncePerSession })} /><Field label="Position"><select value={settings.popupPosition} onChange={(event) => update({ popupPosition: event.target.value as ReviewSliderSettings["popupPosition"] })}><option value="bottom-left">Bottom left</option><option value="bottom-right">Bottom right</option></select></Field><div className={styles.two}><Field label="First appearance (seconds)"><input type="number" min="2" max="120" value={settings.popupDelaySeconds} onChange={(event) => update({ popupDelaySeconds: Number(event.target.value) })} /></Field><Field label="Visible for (seconds)"><input type="number" min="4" max="30" value={settings.popupDurationSeconds} onChange={(event) => update({ popupDurationSeconds: Number(event.target.value) })} /></Field></div>{!settings.popupOncePerSession ? <Field label="Repeat every (seconds)"><input type="number" min="15" max="3600" value={settings.popupIntervalSeconds} onChange={(event) => update({ popupIntervalSeconds: Number(event.target.value) })} /></Field> : null}<small>Popups are disabled automatically for visitors who prefer reduced motion.</small></Panel>; }

function PublishPanel({ settings, update }: EditorProps) { const component = componentFor(settings.widgetType); return <><Panel title="Publishing"><Check label="Enable public review widgets" checked={settings.enabled} onChange={(enabled) => update({ enabled })} /><p className={styles.help}>Use the configured default anywhere:</p><code className={styles.code}>{`<GoogleReviewWidget />`}</code><p className={styles.help}>Or force this layout for a specific placement:</p><code className={styles.code}>{`<${component} />`}</code></Panel><Panel title="Review call to action"><Check label="Show review button" checked={settings.showReviewButton} onChange={(showReviewButton) => update({ showReviewButton })} /><Field label="Button label"><input value={settings.reviewButtonLabel} onChange={(event) => update({ reviewButtonLabel: event.target.value })} /></Field><Field label="Google review URL"><input type="url" placeholder="https://g.page/r/.../review" value={settings.reviewButtonUrl} onChange={(event) => update({ reviewButtonUrl: event.target.value })} /></Field></Panel></>; }

type EditorProps = { settings: ReviewSliderSettings; update: (patch: Partial<ReviewSliderSettings>) => void };
function Panel({ title, description, children }: { title: string; description?: string; children: ReactNode }) { return <section><h2>{title}</h2>{description ? <p className={styles.description}>{description}</p> : null}{children}</section>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className={styles.field}><span>{label}</span>{children}</label>; }
function Check({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className={styles.check}><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} />{label}</label>; }
function humanize(value: string) { return value.replace(/([A-Z])/g, " $1").replace(/^./, (letter) => letter.toUpperCase()); }
function componentFor(type: ReviewWidgetType) { if (type === "carousel") return "GoogleReviewSlider"; if (type === "cards" || type === "masonry" || type === "list" || type === "single" || type === "spotlight") return `GoogleReviewWidget type="${type}"`; if (type === "table") return "GoogleReviewTable"; return "GoogleReviewBadge"; }
