import Link from 'next/link';
import { Phone, MapPin } from 'lucide-react';
import { SiteNav, Brand } from '@/components/site-nav';
import { getSiteSettings } from '@/db/site-data';

export const dynamic = 'force-dynamic';
export default async function PublicLayout({ children }: { children: React.ReactNode }) {
  const settings = await getSiteSettings();
  return <><a href="#main" className="sr-only focus:not-sr-only focus:fixed focus:z-50 focus:bg-white focus:p-4">Skip to content</a><div className="bg-accent text-accent-foreground"><div className="site-container flex min-h-10 items-center justify-between gap-4 text-xs sm:text-sm"><span className="flex items-center gap-2"><MapPin size={14}/> Veteran-owned • Central Minnesota</span><a className="flex items-center gap-2 whitespace-nowrap" href={`tel:${settings.phone.replace(/\D/g, '')}`}><Phone size={13}/>{settings.phone}</a></div></div><SiteNav/><main id="main">{children}</main><footer className="brand-rule bg-[#121110] py-16 text-white"><div className="site-container"><div className="grid gap-12 md:grid-cols-[1.5fr_1fr_1fr]"><div><Brand/><p className="mt-6 max-w-xs leading-relaxed text-white/70">Your yard, crime scene clean.<br/>Veteran-owned. Detail-obsessed. Locally rooted.</p><p className="mt-6 text-sm text-white/70">St. Cloud · Sartell · Sauk Rapids · St. Joseph</p></div><div><h2 className="mb-5 text-sm font-bold uppercase tracking-widest text-[#FFB600]">Take a look around</h2><nav aria-label="Footer navigation" className="grid gap-3">{[['Our services','/services'],['Our story','/about'],['Where we scoop','/service-areas'],['Common questions','/faq'],['Request a quote','/contact']].map(([label, href]) => <Link key={href} href={href} className="w-fit hover:underline">{label}</Link>)}</nav></div><div><h2 className="mb-5 text-sm font-bold uppercase tracking-widest text-[#FFB600]">Talk to a local</h2><a className="block text-2xl" href={`tel:${settings.phone.replace(/\D/g,'')}`}>{settings.phone}</a><a className="mt-3 block break-all text-white/80" href={`mailto:${settings.email}`}>{settings.email}</a><p className="mt-6 text-sm leading-relaxed text-white/70">Have a question before you sign up?<br/>We’re happy to talk it through.</p></div></div><div className="mt-14 flex flex-wrap justify-between gap-4 border-t border-white/20 pt-6 text-xs text-white/60"><p>© {new Date().getFullYear()} K9 Kleanup. All rights reserved.</p><div className="flex gap-6"><Link href="/photo-credits">Photography</Link><Link href="/admin">Team login</Link></div></div></div></footer></>;
}
